{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openmirth-console.fullname" . }}
  labels:
    {{- include "openmirth-console.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openmirth-console.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingressFromNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
      ports:
        - protocol: TCP
          port: 3030
    {{- end }}
  egress:
    # DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Mirth namespace (HTTPS)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.egressMirthNamespace }}
      ports:
        - protocol: TCP
          port: 8443
{{- end }}
